name: build
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request: {}
jobs:
  build:
    name: GO QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: checkout source code
        uses: actions/checkout@v2

      - name: go build
        run: go build .

      - name: go test
        run: go test -v .