name: Build and test Go
on: [ push, pull_request ]
jobs:
  build:
    name: GO QA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x ]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: checkout source code
        uses: actions/checkout@v1

      - name: go build
        run: go build .

      - name: go test
        run: go test -v .